### ISSUE TITLE
Uncaught exception in async event.

### ISSUE THREAD

**Issue by Yumonra07** [hgourvest/node-firebird#105]
There is an uncaught exception on [line 3795 of index.js](https://github.com/hgourvest/node-firebird/blob/master/lib/index.js#L3795). This function is called from an async event, that listens on TCP.read which makes it a nightmare to catch this error from the application code.

AFAIU this error occurs when there is a null value [at this line](https://github.com/hgourvest/node-firebird/blob/master/lib/index.js#L3678) which causes the prms array to have a null value(set from [this line](https://github.com/hgourvest/node-firebird/blob/master/lib/index.js#L3707)). I didn't try changing the line 3707 to `new SQLParamNull(null)`, instead of `null`. Since this error occured randomly for me, i wouldn't have the chance to debug.

How can we fix this error without breaking the construction of `msg` in `executeStatement`? I had to create a wrapper function to sanitize database.query function's inputs, so there wouldn't be any null values.
#### Exception

```
TypeError: prms[i].encode is not a function
    at /var/www/html/service-account/node_modules/node-firebird/lib/index.js:3795:25
    at done (/var/www/html/service-account/node_modules/node-firebird/lib/index.js:3618:17)
    at PrepareParams (/var/www/html/service-account/node_modules/node-firebird/lib/index.js:3756:25)
    at Connection.executeStatement (/var/www/html/service-account/node_modules/node-firebird/lib/index.js:3779:9)
    at Statement.execute (/var/www/html/service-account/node_modules/node-firebird/lib/index.js:1281:21)
    at /var/www/html/service-account/node_modules/node-firebird/lib/index.js:1340:19
    at /var/www/html/service-account/node_modules/node-firebird/lib/index.js:3575:13
    at doCallback (/var/www/html/service-account/node_modules/node-firebird/lib/index.js:1237:5)
    at Socket.<anonymous> (/var/www/html/service-account/node_modules/node-firebird/lib/index.js:2932:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
```

**Comment by Yumonra07** [comment]
This seems to be happening when you give `undefined` params to your queries. I found out this was because , there is currently a check in `PrepareStatement` that checks if the parameter is strict equal to null, but doesn't check if its equal to undefined.

This causes undefined values to get into the second switch case statement in the `PrepareStatement` function. If the type of the column for the `undefined` param isn't one of `[SQL_BLOB, SQL_TIMESTAMP, SQL_TYPE_DATE, SQL_TYPE_TIME]` the param is set to `SQLVarNull`. `SQLVarNull` is derived from SQLVarText so it doesn't have `encode` function, but it does have a `calcBlr`. I fixed this by adding a undefined check that would cause `undefined || null` values getting wrapped in SQLParamXXX, according to their column's type.

You can see my pull request for the details.

**Comment by ericlovescode** [comment]
I have noticed the same thing. For me, this error always happens when my application is idle for some time. Say 5 minutes. My own session is 30 minutes so I don't think it's this. Does node-firebird have it's own session-time independent of the underlying application? Would seem strange if it did.
