### ISSUE TITLE
Various bugfixes in PR #104

### ISSUE THREAD

**Issue by igorklopov** [hgourvest/node-firebird#107]
Please discuss and merge #104

**Comment by hgourvest** [comment]
I think it should be merged.

**Comment by igorklopov** [comment]
Thanks! Pease merge. Looking forward to see it on npm.

**Comment by hgourvest** [comment]
Actually, I do not maintaining this project myself, I give my opinion on this because I originally written this code, final decision now rely on @mariuz and @petersirka .

**Comment by mariuz** [comment]
Merged , I will push it to npm
