### ISSUE TITLE
Webpack compatibility

### ISSUE THREAD

**Issue by duzenko** [hgourvest/node-firebird#114]
I'm trying to use your package in a webpack-based project.

Here's my error
```
ERROR in (webpack)/~/watchpack/~/graceful-fs/fs.js
Module not found: Error: Cannot resolve module 'fs' in D:\dev\pos\Source\web\node_modules\webpack\node_modules\watchpack\node_modules\graceful-fs
 @ (webpack)/~/watchpack/~/graceful-fs/fs.js 3:9-22
```
Is there any way to make it work with node-firebird?

**Comment by mariuz** [comment]
See the related 

https://github.com/pugjs/pug-loader/issues/8

try adding

```
node: {
  fs: "empty"
}

```
to your webpack config

**Comment by duzenko** [comment]
I did my research. That does not help.

**Comment by duzenko** [comment]
My bad.
I tried to call firebird on the client side.
Closed.
