### ISSUE TITLE
Support of Firebird Events

### ISSUE THREAD

**Issue by pabloruan0710** [hgourvest/node-firebird#115]
this library have support for firebird events in trigger post_event?

create trigger nametriger
as
begin
  POST_EVENT = 'new_record';
end

**Comment by sdnetwork** [comment]
not for the moment

**Comment by jacobalberty** [comment]
sdnetwork, is there any documentation on how events are implemented in protocol? I might be able to come up with a PR implementing them if I can find such.

**Comment by sdnetwork** [comment]
yes, i have this document (page 19)
[FirebirdWireProtocol.pdf](https://github.com/hgourvest/node-firebird/files/737620/FirebirdWireProtocol.pdf)

**Comment by jacobalberty** [comment]
Thank you, I'll look at it and see if it is something I can do in my free time.

**Comment by sdnetwork** [comment]
good news it's done you can try on https://github.com/sdnetwork/node-firebird

    db.attachEvent( function (err, evtmgr) {
        if (err)
            return console.log('Error : ', err);

        evtmgr.on('post_event', function (name, count) {
            console.log("rec event", name, count);           
        })

        evtmgr.registerEvent(["evt1", "evt2"], function (err) {
            console.log('ready to receive evt1 and evt2')
        })

        evtmgr.unregisterEvent(["evt1"], function (err) {
             console.log('remove evt1, after that you only receive evt2')
        })
    })

**Comment by pabloruan0710** [comment]
Thanks! @sdnetwork

**Comment by slachtar** [comment]
Nice to see that.

**Comment by pabloruan0710** [comment]
@sdnetwork I Have a problem when using dns name in host
![screen shot 2017-03-20 at 15 43 01](https://cloud.githubusercontent.com/assets/8368140/24115992/f1c718f0-0d83-11e7-8f2f-f1e1b8f2c79e.png)

**Comment by sdnetwork** [comment]
@pabloruan0710 can you do a console.log of socket_info.host please and socket_info.family please ?

i try with localhost and it works (maybe an ipv6 problem)

**Comment by pabloruan0710** [comment]
@sdnetwork socket_info.host is undefined

> TypeError: Cannot read property 'host' of undefined
    at /home/primesoftware/web/user/public_html/dash/node_modules/node-firebird/lib/index.js:1751:55
    at doError (/home/primesoftware/web/user/public_html/dash/node_modules/node-firebird/lib/index.js:1378:9)
    at cb (/home/primesoftware/web/user/public_html/dash/node_modules/node-firebird/lib/index.js:4525:13)
    at doCallback (/home/primesoftware/web/user/public_html/dash/node_modules/node-firebird/lib/index.js:1368:9)
    at /home/primesoftware/web/user/public_html/dash/node_modules/node-firebird/lib/index.js:3336:25
    at /home/primesoftware/web/user/public_html/dash/node_modules/node-firebird/lib/messages.js:151:25
    at search (/home/primesoftware/web/user/public_html/dash/node_modules/node-firebird/lib/messages.js:117:13)
    at /home/primesoftware/web/user/public_html/dash/node_modules/node-firebird/lib/messages.js:54:21
    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)

**Comment by sdnetwork** [comment]
it seems you got an error please replace with that and post result : 

    Connection.prototype.connectRequest = function (callback) {
    var self = this;
    if (self._isClosed)
        return this.throwClosed(callback);
    var msg = self._msg;
    msg.pos = 0;
    msg.addInt(op_connect_request);
    msg.addInt(1); // async
    msg.addInt(self.dbhandle);
    msg.addInt(0);
    function cb(err, ret) {
        console.log(err);
        if (err) {
            doError(err, callback);
            return;
        }

        var socket_info = {
            family : ret.buffer.readInt16BE(0),
            port : ret.buffer.readUInt16BE(2),
            host : ret.buffer.readInt8(4) + '.' + ret.buffer.readInt8(5) + '.' + ret.buffer.readInt8(6) + '.' + ret.buffer.readInt8(7)
        }
        console.log(socket_info);
        doCallback(socket_info, callback);
    }
    this._queueEvent(cb);
    }

**Comment by pabloruan0710** [comment]
undefined
{ family: 512, port: 3051, host: '-64.-88.1.102' }

**Comment by sdnetwork** [comment]
ok thanks,

can you try to replace 

    host : ret.buffer.readInt8(4) + '.' + ret.buffer.readInt8(5) + '.' + ret.buffer.readInt8(6) + '.' + ret.buffer.readInt8(7);
 
with that : 

    host : ret.buffer.readUInt8(4) + '.' + ret.buffer.readUInt8(5) + '.' + ret.buffer.readUInt8(6) + '.' + ret.buffer.readUInt8(7)

and if it doesn't work could you post : console.log(ret.buffer)

**Comment by pabloruan0710** [comment]
Thanks!! works fine!!

**Comment by Drowlex** [comment]
> Thanks!! works fine!!

Hi @pabloruan0710.

I am trying to use this event to catch when an update is carried out in the database and perform an event in my code, you could advise me on how to implement, I have downloaded the branch that has this function and added what they comment, but even can't detect the triggers when they run.

I hope you can help me, thanks.

**Comment by lukaas25** [comment]
Hi @sdnetwork, i'm use the node-firebird and the need to listen for events arises, when using flamerobin I see that the events are generated, but I cannot hear on the node. Is there any way to help me? Thank you very much. I'm Brazilian, sorry for my English

**Comment by lukaas25** [comment]
Hi @sdnetwork, use the node-firebird and increase the need to listen for events, when using or flamerobin to see what events are generated, but it is not possible to listen on the node. Is there any way to help me? Thank you very much. I'm Brazilian, sorry for my English
