### ISSUE TITLE
Express.js REST & node-firebird

### ISSUE THREAD

**Issue by laoyulong** [hgourvest/node-firebird#116]
For the last two months I have been constantly battling issues affecting my Express.js REST server -- I have 10 people constantly using a front-end to connected to it, sending couple o'hundred requests per minute.  After a while it spawns an uncaughtException, shuts the process down and my clients are left hanging.  I tried using forever, but the same thing happened over and over again, so I decided to switch to pm2 and just monitor the server. Example stack trace:
` uncaughtException: Maximum call stack size exceeded date=Wed Nov 02 2016 22:53:06 GMT+0200 (EET), pid=23234, uid=1001, gid=1001, cwd=/usr/home/userName, execPath=/usr/local/bin/node, version=v5.9.1, argv=[/usr/local/bin/node, /usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js], rss=45563904, heapTotal=19876328, heapUsed=15798896, loadavg=[0.40869140625, 0.30859375, 0.21923828125], uptime=3040646, trace=[column=22, file=_stream_writable.js, function=onwriteError, line=305, method=null, native=false, column=5, file=_stream_writable.js, function=onwrite, line=331, method=null, native=false, column=5, file=_stream_writable.js, function=WritableState.onwrite, line=89, method=onwrite, native=false, column=13, file=net.js, function=fireErrorCallbacks, line=450, method=null, native=false, column=5, file=net.js, function=Socket._destroy, line=459, method=_destroy, native=false, column=10, file=net.js, function=Socket._writeGeneric, line=648, method=_writeGeneric, native=false, column=8, file=net.js, function=Socket._write, line=700, method=_write, native=false, column=12, file=_stream_writable.js, function=doWrite, line=301, method=null, native=false, column=5, file=_stream_writable.js, function=writeOrBuffer, line=287, method=null, native=false, column=11, file=_stream_writable.js, function=Socket.Writable.write, line=215, method=Writable.write, native=false], stack=[RangeError: Maximum call stack size exceeded,     at onwriteError (_stream_writable.js:305:22),     at onwrite (_stream_writable.js:331:5),     at WritableState.onwrite (_stream_writable.js:89:5),     at fireErrorCallbacks (net.js:450:13),     at Socket._destroy (net.js:459:5),     at Socket._writeGeneric (net.js:648:10),     at Socket._write (net.js:700:8),     at doWrite (_stream_writable.js:301:12),     at writeOrBuffer (_stream_writable.js:287:5),     at Socket.Writable.write (_stream_writable.js:215:11)]
`

or 

` uncaughtException: Maximum call stack size exceeded date=Fri Oct 28 2016 23:52:57 GMT+0300 (EEST), pid=44099, uid=1001, gid=1001, cwd=/usr/home/userName, execPath=/usr/local/bin/node, version=v5.9.1, argv=[/usr/local/bin/node, /usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js], rss=44609536, heapTotal=20908264, heapUsed=17496752, loadavg=[0.17578125, 0.26171875, 0.2138671875], uptime=2608637, trace=[column=28, file=node.js, function=new TickObject, line=445, method=null, native=false, column=26, file=node.js, function=process.nextTick, line=461, method=nextTick, native=false, column=13, file=_stream_writable.js, function=onwriteError, line=308, method=null, native=false, column=5, file=_stream_writable.js, function=onwrite, line=331, method=null, native=false, column=5, file=_stream_writable.js, function=WritableState.onwrite, line=89, method=onwrite, native=false, column=13, file=net.js, function=fireErrorCallbacks, line=450, method=null, native=false, column=5, file=net.js, function=Socket._destroy, line=459, method=_destroy, native=false, column=10, file=net.js, function=Socket._writeGeneric, line=648, method=_writeGeneric, native=false, column=8, file=net.js, function=Socket._write, line=700, method=_write, native=false, column=12, file=_stream_writable.js, function=doWrite, line=301, method=null, native=false], stack=[RangeError: Maximum call stack size exceeded,     at new TickObject (node.js:445:28),     at process.nextTick (node.js:461:26),     at onwriteError (_stream_writable.js:308:13),     at onwrite (_stream_writable.js:331:5),     at WritableState.onwrite (_stream_writable.js:89:5),     at fireErrorCallbacks (net.js:450:13),     at Socket._destroy (net.js:459:5),     at Socket._writeGeneric (net.js:648:10),     at Socket._write (net.js:700:8),     at doWrite (_stream_writable.js:301:12)]`

You can find the full listings [here](https://gist.github.com/laoyulong/d48e8dd38a6a9ed073f4972d16e45cb1).

**Comment by johnymachine** [comment]
Cant really help with this. But can you provide some samples using node-firebird with Express.js?

Much appreciate!.

**Comment by laoyulong** [comment]
I am sorry, I had it uploaded to Geekli.st, but the Git service is down; Will re-upload them tomorrow morning

**Comment by johnymachine** [comment]
@laoyulong Any progress? I am having problems with persisting connection for endpoints...

**Comment by laoyulong** [comment]
@johnymachine I am so sorry for the delay, but was away for a long time. Anyway, if you check the link in the OP it is now pointing to a gist that contains enough code, so that the error can be reproduced.
