### ISSUE TITLE
Datetime returned as string

### ISSUE THREAD

**Issue by swdevlin** [hgourvest/node-firebird#126]
Hi,

When I issue a select statement that has datetime fields, those fields are being returned as a string instead of a Date object.

How do I get a date object out of the query?

Thanks.

**Comment by mreis1** [comment]
Like this  "2017-02-09T12:42:58.180Z"?
Well all you have to do is new Date("2017-02-09T12:42:58.180Z") and you have your Date object.

**Comment by swdevlin** [comment]
Yes, that is the format. While I can do the assignment myself I would need to code every field. I am hoping that the library would know the field type and do the conversion automatically, like it does for strings and numbers.

**Comment by mreis1** [comment]
I understand, it makes sense.

**Comment by swdevlin** [comment]
Sigh.

Never mind this request. I found out some other place in our code is changing the format. A Date object is returned by the db driver.
