### ISSUE TITLE
Node.js application stops when Firebird server is restarted

### ISSUE THREAD

**Issue by jdubbeldam** [hgourvest/node-firebird#127]
I'm using node-firebird with the pooling option. When my Firebird server stops or restarts my Node.js application stops. 

I can see that the reconnection part starting on line 2832 in index.js causes a recursion of the callback function passed to the new Connection object. 

How can this be avoided?

Minor detail: I think the code at line 2839 in index.js should be:
ctx.connect(self.options.database || self.options.filename, function(err) {

**Comment by sdnetwork** [comment]
have you try with this https://github.com/sdnetwork/node-firebird, it should fix this problem

**Comment by jdubbeldam** [comment]
I tested your proposed new version and it fixed the problem. Thank you very much for your time to fix the problem.
