### ISSUE TITLE
string overflow on query

### ISSUE THREAD

**Issue by swdevlin** [hgourvest/node-firebird#130]
Hi,

I have an ID column in a INVOICE table in my database. The column uses the DM_UUID domain, which is :

`CREATE DOMAIN DM_UUID AS VARCHAR(24) CHARACTER SET UTF8;`

When I run the following query:

`sql = 'select id from invoice where id = ?'`

with parameter

`eCxH.mSBIaPBJvTsvIlHLk`

I get an error `Dynamic SQL Error, SQL error code = -303, arithmetic exception, numeric overflow, or string truncation, string right truncation`

When I run the query this way

`sql = "select id from invoice where id = 'eCxH.mSBIaPBJvTsvIlHLk'";`

the query works.

Any ideas?

Thanks.

**Comment by swdevlin** [comment]
Please disregard. Worked out the problem.

**Comment by cardinal-II** [comment]
@swdevlin 
How did you solve the problem?
