### ISSUE TITLE
Error: Connection is closed. with Firebird 3.0 on Windows 10

### ISSUE THREAD

**Issue by ggyczew** [hgourvest/node-firebird#133]
I've started setup of workspace for new project (Firebird + Node + Total.js + Node-Firebird).
I've chosen FB 3.0 (64bit) version but could not test connection because of "Error: Connection is closed.
Even tough I added to firebird.conf (3.0) suggested
AuthServer = Legacy_Auth
WireCrypt = Disabled

Then I changed server to FB 2.5 (64bit) and test script worked as supposed.

What's wrong with Firebird 3.0? Is it possible to make this setup work with latest Firebird version.

**Comment by mariuz** [comment]
you need to open port https://askubuntu.com/a/427523/65302
