### ISSUE TITLE
Undetected dropped connection with long running pooling connections

### ISSUE THREAD

**Issue by jdubbeldam** [hgourvest/node-firebird#138]
When I use node-firebird in pooling mode in a long running script, I notice that after a while that the (pool) connections don't react to requests any more. My guess is that the Firebird server has dropped the tcp connection(s) (error 10054) and that this is not noticed by the node-firebird library.

**Comment by sdnetwork** [comment]
can you try with : 

https://github.com/sdnetwork/node-firebird

**Comment by jdubbeldam** [comment]
Thank you for your reply. The libraries look identical. What's the difference between the two, and has your suggested library fixed my discribed problem?

**Comment by sl1mpshady** [comment]
waiting for a reply..

**Comment by Tomas2D** [comment]
Any progress on it?

**Comment by Tomas2D** [comment]
We can probably close this for now.
