### ISSUE TITLE
Get columns names when query returns no results.

### ISSUE THREAD

**Issue by malpacasville** [hgourvest/node-firebird#145]
Hi, This is more just a question than an "Issue".

Is there a way of getting the column names when the query returns no records?

I'd like to migrate away from an api service that returns an empty record instead of an empty array when there are no results. e.g. ["Field1": "", "Field2": ""] instead of [].
Too much of my code now checks Data[0].KeyField !== "" to identify an empty record, that it would be much easier for me to simulate the api's behaviour than to find all those tests to do Data.length !== 0.

Hope that makes sense.
Thanks.

**Comment by vvvait** [comment]
Hi. Just add in index.js after this lines:
```
if (custom.asObject && !data.fcols) {
  data.fcols = [];
  for (var i = 0, length = output.length; i < length; i++) {
    data.fcols.push(lowercase_keys ? output[i].alias.toLowerCase() : output[i].alias);
  }
}                
```
that line 
`statement.connection.db.emit("columns", data.fcols);`

using:

```
query(owner: Database, asArray: boolean, sql: string, params: any[] = []) {
    return new Promise<IQueryResult>((resolve, reject) => {
      let header: any = null;
      (owner as any).once("columns", (columns: any) => header = columns);
      const cb = (err: any, rows: any[]|undefined) => {
        if (err) {
          doError("query", err, sql, params);
          reject(err);
        } else {
          if (!Array.isArray(rows))
            resolve({ header, returning: rows });
          else
            resolve({ header, rows });
        }
      };
      if (asArray) 
        owner.execute(sql, params, cb);
      else 
        owner.query(sql, params, cb);
    });
  },
```

**Comment by malpacasville** [comment]
Great thanks! Still relevant haha.
