### ISSUE TITLE
integrate sdnetwork/node-firebird improvements and fixes?

### ISSUE THREAD

**Issue by kattunga** [hgourvest/node-firebird#151]
Hi,

I created a wrapper class around node-firebird that use promises so you can use async await in node 8.x and up.
The problem is that I can only make it work with https://github.com/sdnetwork/node-firebird repository because it has several bug fixes and it correctly manage blobs fields.

It's possible to integrate those bugfixes to the proyect.
The only other alternative is to publish a new npm-package with a different name.

Regards

**Comment by mariuz** [comment]
@kattunga , I will merge the @sdnetwork work if he makes a pull request
