### ISSUE TITLE
block size exceeds

### ISSUE THREAD

**Issue by isaquer** [hgourvest/node-firebird#155]
Hi follows the error below,
" Dynamic SQL Error, SQL error code = -204, Implementation limit exceeded, block size exceeds implementation restriction "

Error does not happen due to UTF-8 charset.

**Comment by ericlovescode** [comment]
I get this sometimes when my programs try to access FB concurrently using
same connection. Check all your callbacks and async processes.

**Comment by isaquer** [comment]
The calls are correct, the problem is that there are very large varchar fields that UTF-8 does not support. In order to use precise I need to define the connection encoding as ISO8859_1
