### ISSUE TITLE
Error: I/O error during "open" operation for file

### ISSUE THREAD

**Issue by ulises256** [hgourvest/node-firebird#158]
i can't connect to the database..

var Firebird = require('node-firebird');

    options.host = '127.0.0.1';
    options.port = 3050;
    options.database = './firebird/ver1/SAE70EMPRE09.FDB';
    options.user = 'sysdba';
    options.password = 'masterkey';

Firebird.create(options, function(err, db) { console.log(db) });

**Comment by mariuz** [comment]
This is file permission issues , not driver related https://stackoverflow.com/questions/29942639/firebird-error-while-trying-to-create-file-permission-denied
