### ISSUE TITLE
NODE: 16373 - Your user name and password are not defined.

### ISSUE THREAD

**Issue by tgiovanella87** [hgourvest/node-firebird#167]
Good morning.
I'am using this package on a project and its working really fine until now. 
In the production server i'm experiencing this error message.

(node:16373) UnhandledPromiseRejectionWarning: Error: Your user name and password are not defined. Ask your database administrator to set up a Firebird login.

I am shure that the username and password is ok because i use it on my SGBD IDE. The diference in this case are that the Firebird at the production server is 3.0 running on linux and the dev server is Firebird 3.0 running on Windows.

**Comment by mrotteveel** [comment]
If you are using Firebird 3, you need to create a legacy auth user (and make sure Firebird 3 is configured to support legacy auth users). See also the note at the end of the readme.
