### ISSUE TITLE
Support of Firebird attachEvents

### ISSUE THREAD

**Issue by Drowlex** [hgourvest/node-firebird#172]
Hello, I am trying to use your library, but I have problems since I cannot detect the trigger, it never entered the "on" event.
I am looking for some example of how to carry out this process, but I find only a few examples simple with  this:

            db.attachEvent( function (err, evtmgr) {
                // console.log(evtmgr);

                if (err)
                    return console.log('Error : ', err);
            
                evtmgr.on('POST_EVENT', function (name, count) {
                    console.log("rec event", name, count);           
                })
            
                evtmgr.registerEvent(["evt1", "evt2"], function (err) {
                    console.log('ready to receive evt1 and evt2')
                })
            
                evtmgr.unregisterEvent(["evt1"], function (err) {
                     console.log('remove evt1, after that you only receive evt2')
                })
            });

I added the trigger "POST_EVENT" in the database, without any process, just to launch it to try to obtain it, I don't know if this equally affects the method, or if I'm waiting for something else.

Trigger implemented:

    CREATE OR ALTER TRIGGER "POST_EVENT" FOR PARTIDASLOG
    ACTIVE BEFORE INSERT POSITION 0
    AS
    begin
    /* Trigger text */
    end
    ^
    SET TERM ; ^

**Comment by jacobalberty** [comment]
I don't believe this branch supports POST_EVENT at all, the sdnetwork fork does see: https://github.com/sdnetwork/node-firebird

**Comment by Drowlex** [comment]
> No creo que esta rama sea compatible con POST_EVENT en absoluto, la bifurcación sdnetwork sí ve: https://github.com/sdnetwork/node-firebird

**Comment by Drowlex** [comment]
> I don't believe this branch supports POST_EVENT at all, the sdnetwork fork does see: https://github.com/sdnetwork/node-firebird

That's right, it is not compatible, download a previous branch, however the event does not work, or maybe I am implementing it incorrectly since it fails to detect it, that's why I was I was doing this question.

**Comment by Drowlex** [comment]
The version i download if you have the elements to perform this event, however when the trigger is executed, the event:  'post_event' is not detected.
I hope you can help me regarding this, thanks .
