### ISSUE TITLE
I cannot make a connection - Error: Your user name and password are not defined. 

### ISSUE THREAD

**Issue by AndreyPootMay** [hgourvest/node-firebird#175]
Hello everyone, I am trying to do a crud using firebird for practice reasons, I have used the code that you have in your examples but I cannot make a connection between the database and node-js, it seems my firebird port is correctly, the path to the fdb file is correct, the username and password are also correct.

#### My Code:

```js
var firebird=require('node-firebird');

// opciones base de datos
var options = {};

options.host = '127.0.0.1';
options.port = 3050;
options.database = '/var/www/html/crud-firebird/src/people.fdb';
options.user = 'SYSDBA';
options.password = 'programador';

console.log(options);

firebird.attach(options, function(err, db) { 
    if (err)
        throw err;

    // db = DATABASE
    db.query('SELECT * FROM CUSTOMER', function(err, result) {
        // IMPORTANT: close the connection
        db.detach();
    });
});
```
I read the readme.md and noticed that my version of firebird (3.0) uses special parameters within firebird.conf. I put them on, however I got the following error:
```bash
/var/www/html/crud-firebird/db.js:16
        throw err;
        ^

Error: Your user name and password are not defined. Ask your database administrator to set up a Firebird login.
    at doCallback (/var/www/html/crud-firebird/node_modules/node-firebird/lib/index.js:1234:18)
    at /var/www/html/crud-firebird/node_modules/node-firebird/lib/index.js:2929:21
    at /var/www/html/crud-firebird/node_modules/node-firebird/lib/messages.js:151:25
    at search (/var/www/html/crud-firebird/node_modules/node-firebird/lib/messages.js:117:13)
    at /var/www/html/crud-firebird/node_modules/node-firebird/lib/messages.js:54:21
```

However if I log-in inside the isql-fb manager I got the access to the database:

![image](https://user-images.githubusercontent.com/28898216/66366865-72dca480-e957-11e9-8981-20028dcfe517.png)

I would love to know if there are other commands to run for the database manager or if it is a configuration of my node (version 12.10.0).

Operating system: Linux Lite 4.4

**Comment by hugobereta** [comment]
When you use that params, your sysdba password get back to the default "masterkey".
