### ISSUE TITLE
Callback never called when have error in procedure

### ISSUE THREAD

**Issue by Erick-Zanetti** [hgourvest/node-firebird#177]
See a example that procedure:
```
create or alter procedure TESTE_NODE
returns (
    RETORNO integer)
as
begin

  RETORNO = 10;
  suspend;

  RETORNO = 10 / 2;
  suspend;

  RETORNO = 0 / 0;
  suspend;
end
```
obvious this procedure have error in third return, but in ibexpert I receive this:
![image](https://user-images.githubusercontent.com/29898441/67701473-c35f8480-f98e-11e9-806c-5a37de4013cb.png)
and this:
![image](https://user-images.githubusercontent.com/29898441/67701502-ceb2b000-f98e-11e9-813c-ae2811215717.png)

But the problem is in my node application, because my callback never was called.
My code is:
```
        return new Promise((resolve, reject) => {
            let sql = "select RETORNO from TESTE_NODE ";
            let params = [];
            console.log('1');
            db.query(sql, params, (err, result) => {
                console.log('2');
                if (err) return reject(err);
                resolve(result);
            });
        });
```
My console print only 1.

Of course this a error in my procedure, but is very difficult debug and get the error when I dont have a return of error, so I need a solution.

**Comment by LuizzTrevisan** [comment]
👍
