### ISSUE TITLE
Executing a statement hangs when connecting to firebird 1.5

### ISSUE THREAD

**Issue by imccoy** [hgourvest/node-firebird#180]
I work on an app that gets installed at customer sites where we don't have any control over the firebird version in use or the firebird configuration.

I'd like to produce a nice error message when we're trying to connect to firebird 1.5. Unfortunately on my test machine, we can connect successfully but then `connection.query` hangs. I've chased it down to a point where `decodeResponse` throws an exception because it's received the value 352583681 as the current `op` and then fallen through to the `default:` case. Unfortunately, the callback on the socket's `'data`' event handles this exception without calling `cb`.

There's a few potential fixes I can think of:

1. Call `cb` with the `err` in that `'data'` callback.
2. Call `cb` with the `err` in that `'data'` callback, but also shut the whole connection down on the basis that if we got a message we didn't understand, we can't assume that our notion of a frame on the socket aligns with the server's. There may be a bunch of cases where this is overkill.
3. Emit a new `'response-decode-error'` event on the connection when `decodeResponse` throws an exception
4. Emit an `'error'` event on the connection when `decodeResponse` throws an exception

Option 3 has the advantage of being completely backwards-compatible. Options 1 and 2 are most discoverable.

I don't know how important it is to maintain backwards compat in cases where effectively the operation is hanging right now.

It seems possible that doing Options 1 or 2 would mitigate https://github.com/hgourvest/node-firebird/issues/177. Option 2 would potentially be unpleasantly surprising for that case.

I think Option 1 might be best. What do you think?

**Comment by henry701** [comment]
This also occurs on firebird **2.0.7** on my machine (Windows 10 x64) and I was able to find this response by tracking down the error to the exact same spot.
