### ISSUE TITLE
Do not work database

### ISSUE THREAD

**Issue by Apxucmpax** [hgourvest/node-firebird#181]
Good day. I have a problem connecting to the database. I can’t connect to the finished database and I can’t create a new one. Please tell me what could be the problem.
At first I wanted to connect to an existing DB, but I got an error:
> Error: Your user name and password are not defined. Ask your database administrator to set up a Firebird login.

Although I freely connected to the DB through the DBeaver with the same parameters as in the options.
Then I suggested that something was wrong with my database and decided to create a new database using the application, but ran into the same problem.
Below you can see the code and the error.
Version Firebird: 3.0.4.33054

My application test.js

```
const Firebird = require('node-firebird');

var options = {};

options.host = 'localhost';
options.port = 3053;
options.database = 'TEST.fdb';
options.user = 'SYSDBA';
options.password = 'masterkey';
options.lowercase_keys = false; // set to true to lowercase keys
options.role = null;            // default
options.pageSize = 4096;        // default when creating database

Firebird.create(options, function(err, db) {

    if (err)
        throw err;

    db.query('SELECT * FROM TABLE', function(err, result) {
        db.detach();
    });
 });
```

My console

> E:\Work\Worfing\Apxu Firebird 2\test.js:17
>         throw err;
>         ^
> 
> Error: Your user name and password are not defined. Ask your database administrator to set up a Firebird login.
>     at doCallback (E:\Work\Worfing\Apxu Firebird 2\node_modules\?[4mnode-firebird?[24m\lib\index.js:1234:18)
>     at E:\Work\Worfing\Apxu Firebird 2\node_modules\?[4mnode-firebird?[24m\lib\index.js:2937:21
>     at E:\Work\Worfing\Apxu Firebird 2\node_modules\?[4mnode-firebird?[24m\lib\messages.js:151:25
>     at search (E:\Work\Worfing\Apxu Firebird 2\node_modules\?[4mnode-firebird?[24m\lib\messages.js:117:13)
>     at E:\Work\Worfing\Apxu Firebird 2\node_modules\?[4mnode-firebird?[24m\lib\messages.js:54:21
> ?[90m    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)?[39m

**Comment by LifeOrYou** [comment]
For connecting to firebird 3, you need to configure your server.
Please see https://github.com/hgourvest/node-firebird#firebird-30-support
