### ISSUE TITLE
Firebird.msg not being loaded on Electron

### ISSUE THREAD

**Issue by joaodforce** [hgourvest/node-firebird#182]
The way that the file firebird.msg file is being loaded does not work if the library is being used in electron. Resulting in query errors not being disclosed.

I've managed to resolve this by using `require.resolve('node-firebird')` in the messages.js file, it resolves the module path instead of assuming the file will be in the same directory.

Also it was very hard to get here, because I did not know if I was not using the library properly or if it was an issue with the library itself, the way that the code handles failing to load this file is very poor, because it does not disclose the error. I've put a console.log(err) in there so we at least know it was an internal library error if the file fails to load again.

![image](https://user-images.githubusercontent.com/9410916/71918699-96370b80-3161-11ea-98bb-8fc175f8c281.png)

**Comment by pcandido** [comment]
Same problem. Maybe the path of firebird.msg should be configured in Firebird.attach.

`Firebird.attach({
   ...,
  messageFile: ''
}, () => {})`

The default could be: `${__dirpath}/firebird.msg`

The file could be included in the bundle using electron config, and the path customized.

This approach enables customize the msg file in other cases.

**Comment by joaodforce** [comment]
I like the approach too, because even with my approach I had problems, the file location will change the node_modules folder is not always available in all development environments.
