### ISSUE TITLE
ERROR INSERT RETURNING  ID

### ISSUE THREAD

**Issue by crisgol** [hgourvest/node-firebird#185]
Feribird Version 3.0.4
Error:  "Cursor is not open"

Action:  INSERT INTO AUTHORS (name) VALUES ('TESTE') RETURNING ID

**Comment by LifeOrYou** [comment]
Insert with returning clause currently not work with firebird 3.

**Comment by maratth** [comment]
@mariuz Fix by #200

**Comment by mariuz** [comment]
Closed , Thank you
