### ISSUE TITLE
error module 'net', help me?

### ISSUE THREAD

**Issue by curruwilla** [hgourvest/node-firebird#189]
I'm not able to connect to a firebird database, the following error appears:

![Anotação 2020-03-20 112301](https://user-images.githubusercontent.com/7454081/77172794-56fc3380-6a9d-11ea-86a6-59013250ed06.jpg)
![Anotação 2020-03-20 112439](https://user-images.githubusercontent.com/7454081/77172844-67141300-6a9d-11ea-9dc3-e261310e5cff.jpg)

**Comment by mariuz** [comment]
net module is only available in node js https://nodejs.org/api/net.html
