### ISSUE TITLE
Sample Restore

### ISSUE THREAD

**Issue by elvispdosreis** [hgourvest/node-firebird#198]
Could you please provide me with a database restore example

**Comment by maratth** [comment]
It's a simple exemple without error handling.

```
const config = {...}; // Clasic configuration with manager = true
const RESTORE_OPTS = {
    database: 'database.fdb",
    files: ['backup.fbk']
};

Firebird.attach(config, (err, srv) => {
    srv.restore(RESTORE_OPTS, (err, data) => {
        data.on('data', () => {});
        data.on('end', () =>
            srv.detach();
        });
    });
});
```

**Comment by mariuz** [comment]
@maratth I have added your example to the Readme 
https://github.com/hgourvest/node-firebird/blob/master/README.md#restore-service-example

I hope is ok :)

**Comment by maratth** [comment]
@mariuz no problem but has quote issue `database: 'database.fdb" <-` here.

I will create a pull request with service testing comming soon, it's containing lot of more exemple of service usage.

**Comment by mariuz** [comment]
Quote is fixed now , please do send more examples of service usage. 

Thank you .
