### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by albanirneves** [hgourvest/node-firebird#210]
When I run a given query in version 0.9.2 I have the following error:

`RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 2867. Received 2880`

However when running version 0.8.9 the results return normally.

Bellow my code:
```
'use strict'; 

const sql = 'select first 5 skip 0 * from JOBS';
const Firebird = require('node-firebird');

const config = {
   database: 'c:/test/jobs.fdb',
   host:     '127.0.0.1',
   port:     '3050',
   user:     'SYSDBA',
   password: 'masterkey',
   role:     null,
   pageSize: 16384,
   timeout:  3000
};

Firebird.attach(config, function (error, db) {
    if (error) {
        console.log(error);
    } else {
        db.query(sql, (error, results) => {
            if (error) {
                console.log(error);
            } else {
                console.log(results);
            }
        });
    }
});
```

**Comment by maratth** [comment]
What is the structure of your jobs table ?

**Comment by albanirneves** [comment]
I realized that this has to do with the database because I exported the data from the same table to another bank and there was no problem. But I have no idea what it is.

**Comment by 3ten** [comment]
I have the same on version 0.9.2
installing 0.8.9v helped for me
