### ISSUE TITLE
Error occurred during login

### ISSUE THREAD

**Issue by josemateuss** [hgourvest/node-firebird#213]
I'm trying to connect to a database in remote server and I got this error: Error occurred during login.

firebird.conf:
`AuthServer = Srp, Legacy_Auth`
`WireCrypt = Disabled`

Any ideas to solve that?

**Comment by gefer** [comment]
Try this:
```AuthServer = Srp, Win_Sspi, Legacy_Auth```
```WireCrypt = Enabled```

**Comment by mariuz** [comment]
Please use the following config 

```
AuthServer = Srp, Legacy_Auth
WireCrypt = Disabled
UserManager = Legacy_UserManager
```

https://firebirdsql.org/file/documentation/release_notes/html/en/3_0/rnfb30-security-new-authentication.html
