### ISSUE TITLE
Incompatible wire encryption levels requested on client and server

### ISSUE THREAD

**Issue by kendi95** [hgourvest/node-firebird#214]
Hi, i'm trying to connecting with my database with Express.
The version of Firebird is v3.0.6

`
//config
options.host = "127.0.0.1";
options.port = 3050;
options.database = "/tmp/firebird/<file-name>.fdb";
options.user = "";
options.password = "";
options.lowercase_keys = false;
options.role = null;
options.pageSize = 4096;

//Trying to connect
Firebird.attach(options, (err, db) => {
	if (err) throw err;

	console.log('Connection successful...');
});

`
Why is it happeninig?

**Comment by maratth** [comment]
What is your WireCrypt configuration on the server ?

**Comment by mariuz** [comment]
please  use WireCrypt = Disabled

**Comment by mariuz** [comment]
Tested and should work also with WireCrypt = enabled , Here is the related comment https://github.com/mvitlov/vscode-db-explorer-firebird/issues/2#issuecomment-477954010

**Comment by blackholeearth** [comment]
after setting   ``WireCrypt = Enabled``    in firebird.conf   **RESTART the firebird service** . from services.msc.

**Comment by CyberT33N** [comment]
https://github.com/CyberT33N/firebird-cheat-sheet/blob/main/README.md#docker-compose
