### ISSUE TITLE
db.sequentially returns duplicates

### ISSUE THREAD

**Issue by fdebef** [hgourvest/node-firebird#232]
After updating from 0.8.9 to 0.9.8 I experience issue with db.sequentially. It returns duplicated rows, even if there are no in database. I didn't find any rule why some of rows appear several times in row callback.
After downgrade to 0.8.10 everything is OK.
I use it in standard way for several years, without any issues. I have tested also the query directly on my Firebird server (2.5) with FlameRobin - no duplicities.
My code: 
```
db.sequentially(
      recordsQuery,
      [],
      (rw, index) => {
// some stuff here
```
I tried it also without empty array in place of parameters.

**Comment by pablofr** [comment]
I'm also with the same duplicity problem

**Comment by jucapablanca** [comment]
This issue has been fixed, please @mapopa close this
