### ISSUE TITLE
Error: blr string is too big (when debugging)

### ISSUE THREAD

**Issue by goulu** [hgourvest/node-firebird#233]
suddenly got the error above after adding some debugging options ...

traced to 
`blr.addString(isc_dpb_process_name, process.title, DEFAULT_ENCODING);`

my process.title (Windows) is very long when debugging ...
and apparently useless, since I successfully replaced process.title by "dummy" ...

**Comment by jucapablanca** [comment]
This issue has been fixed, please @mapopa close this
