### ISSUE TITLE
 db.sequentially does not return data, but "buffers"

### ISSUE THREAD

**Issue by gabrielsoutoabreu** [hgourvest/node-firebird#236]
I need the select data, but what the method returns is these objects with "buffers", how to get the data in fact?

code:
![image](https://user-images.githubusercontent.com/59427536/98851806-8c430080-2435-11eb-9056-59488001275b.png)

result:
![image](https://user-images.githubusercontent.com/59427536/98851870-a086fd80-2435-11eb-9651-cae4ab2b973f.png)

**Comment by jucapablanca** [comment]
If the charset of your table's varchar column is 'NONE', all queries return buffers instead of strings. To correct it, just set the correct charset for the varchar columns. 

Or use this funtion:

exports.buffToStr = function(buf) {
    return String.fromCharCode.apply(null, new Uint16Array(buf));
}; 

@mariuz, @hgourvest  close this Issue.
