### ISSUE TITLE
Error Invalid transaction handle

### ISSUE THREAD

**Issue by WilliamFdaSilva** [hgourvest/node-firebird#237]
## I got an error when trying to Commit in sequence with the same Transaction. 

The first time is commited but the second time I got the following message:

Error: ```invalid transaction handle (expecting explicit transaction start)
    at doCallback (C:\Ultra\PreVendaServerV2\node_modules\node-firebird\lib\index.js:1297:21)
    at C:\Ultra\PreVendaServerV2\node_modules\node-firebird\lib\index.js:3019:25
    at C:\Ultra\PreVendaServerV2\node_modules\node-firebird\lib\messages.js:151:25
    at search (C:\Ultra\PreVendaServerV2\node_modules\node-firebird\lib\messages.js:117:13)
    at C:\Ultra\PreVendaServerV2\node_modules\node-firebird\lib\messages.js:54:21
    at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
    at FSReqCallback.callbackTrampoline (internal/async_hooks.js:126:14) {
  gdscode: 335544332,
  gdsparams: undefined ```

I am inserting the CHILDREN when i got the error message with the same Transaction.

This is my Commit Method:
![SS2](https://user-images.githubusercontent.com/73131640/100141705-97545280-2e71-11eb-94b5-a517aecdb5f8.png)

**Comment by jucapablanca** [comment]
This is not a mistake, if you want to commit the transaction and keep it open, you must use 'commitRetaining' and not 'commit';
