### ISSUE TITLE
Multi-tenant option for firebird connection on multiple databases?

### ISSUE THREAD

**Issue by leodavinci1** [hgourvest/node-firebird#243]
I see that theres an option for pooling but only for one database. Is there a way to connect to multiple databases? Lets say I have 10 folders each with one database file, how can I let a connection open in each one of the 10 files?

**Comment by jucapablanca** [comment]
Is simple:

var optionsDB1 = {};
optionsDB1.host = '127.0.0.1';
optionsDB1.port = 3050;
optionsDB1.database = 'databaseDB1.fdb';
optionsDB1.user = 'SYSDBA';
optionsDB1.password = 'masterkey';

var optionsDB2 = {};
optionsDB2.host = '127.0.0.1';
optionsDB2.port = 3050;
optionsDB2.database = 'databaseDB2.fdb';
optionsDB2.user = 'SYSDBA';
optionsDB2.password = 'masterkey';

If you are using pool:

var poolDB1 = Firebird.pool(5, optionsDB1);
var poolDB2 = Firebird.pool(5, optionsDB2);

or using attach:

Firebird.attach(optionsDB1, function(err, db) {

});

Firebird.attach(optionsDB2, function(err, db) {

});

repeat for as many connections as needed.
