### ISSUE TITLE
Cannot read property 'protocolMinimumType' of undefined

### ISSUE THREAD

**Issue by mkspinto** [hgourvest/node-firebird#250]
Hi folks.

I'm trying to use the `node-firebird` for a first time but without success. I have a Windows Server in my infrastruct in a private IP with the Firebird installed with a existent database created as `CONNECTOR.FDB`. In my development machine i'm trying to execute a simples query but every time I've been receving the same error:

`TypeError: Cannot read property 'protocolMinimumType' of undefined`

Also, I realize that the error are ocurring in `index.js` file at line `3291`.
Can someone help me to undertarding what I'm doing of wrong?

**Comment by mariuz** [comment]
Maybe is a firewall issue you need to verifiy if the port is open for firebird 

https://stackoverflow.com/questions/53623556/error-when-connecting-to-firebird-database-with-nodejs

**Comment by HelderiDBA** [comment]
Helo!

I have the same error here, but I am running everything in a local environment.

Did you solve the problem?

**Comment by mkspinto** [comment]
Hi @HelderiDBA 

Unfortunately I didn't found the reason of this issue, even checking all the necessary points in my infra environment like de Firewall and port communication for example.

So I just abandoned use this NPM lib in NodeJS and jump to develop my integration using C#.
This way worked very well for me.

**Comment by skafy0** [comment]
I'm having the same problem. Did anyone have same problem and resolved it?
Node - Fierbird 0.9.9
Node 14.17.1

**Comment by HelderiDBA** [comment]
I managed to solve it, but I had to add 3 properties in the config file of Firebird:

AuthServer = Srp, Legacy_Auth
WireCrypt = Enabled
UserManager = Srp, Legacy_UserManager

**Comment by skafy0** [comment]
Ok, tnx! 
I've also solved it myself by installing newer version of node. From node 14.17.1 -> 16.3
