### ISSUE TITLE
I can't get the data

### ISSUE THREAD

**Issue by Residentalex** [hgourvest/node-firebird#258]
![image](https://user-images.githubusercontent.com/26370921/127216701-d995f430-4b53-4cfe-af4b-5d1fab58e391.png)

**Comment by Residentalex** [comment]
i'll try to get the result, but nothing

**Comment by Tomas2D** [comment]
Why you are converting an object to a string?

**Comment by jesusvilla** [comment]
Hi @Residentalex

"res" is a array of objects

console.log(res) // [{NOMBRE: '???'}, ...]

Test:
console.log(res[0] && res[0].NOMBRE)
