### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Tomas2D** [hgourvest/node-firebird#261]
Hello, can you please release a new version? 

Thank you.

**Comment by dffrancisco** [comment]
The version in npm is different the github, please update

**Comment by Tomas2D** [comment]
@mariuz

**Comment by mariuz** [comment]
Released 1.0.0 https://www.npmjs.com/package/node-firebird/v/1.0.0  :champagne:

**Comment by ericlovescode** [comment]
Congratulations to all the developers/maintainers for reaching v1.0. Well
done.

**Comment by dffrancisco** [comment]
@mariuz thank you, for update in the npm
