### ISSUE TITLE
How can I get Transaction ID

### ISSUE THREAD

**Issue by FabianoCastro** [hgourvest/node-firebird#286]
Hi, I´m with a problem, Transaction with "infinite wait", but I can't log Transaction ID, to discover where is the problem.

**Comment by Rafatcb** [comment]
You can use `SELECT RDB$GET_CONTEXT('SYSTEM', 'TRANSACTION_ID') AS "transaction_id" FROM RDB$DATABASE` after creating the transaction.

E.g.:

```js
transaction.query(
  `SELECT RDB$GET_CONTEXT('SYSTEM', 'TRANSACTION_ID') AS "transaction_id" FROM RDB$DATABASE`,
  [],
  (result) => {
    console.log('id:', result[0].transaction_id);
  },
);
```
