### ISSUE TITLE
Include encoding WIN1252

### ISSUE THREAD

**Issue by felipedllinfo** [hgourvest/node-firebird#296]
Hi, 
I would like to know if is possible to include the encoding WIN1252. I am from Brazil and this is the charset used here. 

Thank you for attention.

**Comment by mariuz** [comment]
@felipedllinfo 
you can setup at connection level 

https://github.com/hgourvest/node-firebird/pull/272

**Comment by mariuz** [comment]
I have added a notice in the readme 

https://github.com/hgourvest/node-firebird/blob/master/README.md#connection-options
