### ISSUE TITLE
The example program does not exit

### ISSUE THREAD

**Issue by felixrabe** [hgourvest/node-firebird#31]
When I run the example from the README.md, the program does not exit. Is this known and I missed something?

Will provide more information when asked, but as this project looks a bit stale, I won't bother as long as I don't know whether anyone will look at this issue.

**Comment by mloskot** [comment]
FYI, while working on Vagrant setup provisioned with Firebird, I encounter this issue. Espetially, I was glad I found @felixrabe 's comment confirming there is a problem/bug on Ubuntu 14.04 indeed
> just won't do it on Ubuntu 14.04, which I think is a step backwards compared to Ubuntu 12.04

My task was not related to node or node-firebird, but I think you might be interested in solution I have managed to work out. Here is Bash script I run from my Vagrantfile, with complete Firebird 2.5 setup on Ubuntu 14.04: https://github.com/SOCI/soci/blob/master/bin/vagrant/firebird.sh

**Comment by mariuz** [comment]
Seems that in ubuntu 15.10 works without an issue 

apt-get purge firebird2.5* 
apt-get install -qq firebird2.5-superclassic 

I will reccommend the firebird ppa for 15.04 users
