### ISSUE TITLE
sequentially - Reached heap limit Allocation failed

### ISSUE THREAD

**Issue by arthurbolsoni** [hgourvest/node-firebird#313]
I'm trying to fetch a big table, I'm using it sequentially, which says in the readme that it streams the search information; however the memory is never freed and exceeds the heap memory

```
const connection = Firebird.attach(options, function (err: any, db: Firebird.Database) {
    if (err)
        throw err;

    db.sequentially(sql, [],
        (err: any, rows: any) => {
            rows = null;
        },
        (err: any) => {
            db.detach();
        });
});
```

![image](https://github.com/hgourvest/node-firebird/assets/21229921/e7b49802-9c1c-4a08-9605-c6b3454ad85b)

**Comment by mariuz** [comment]
Resolved in the 2.x releases on both fronts:

- `sequentially` genuinely streams without retaining rows — there is a regression test pinning that streamed rows are not buffered into the completion result ("should not buffer all streamed rows in sequentially callback result"). The common accidental retention is collecting rows yourself inside the row callback, or an old version that buffered.
- For real backpressure against a slow consumer, use the `(row, index, next)` form (fetching pauses until you call `next()`), or `db.queryStream()`, which returns an object-mode `Readable` with native backpressure — see [README § Streaming a big data](https://github.com/hgourvest/node-firebird#streaming-a-big-data) including the do/don't guidance.

Closing — please reopen with a heap snapshot if 2.x still grows unbounded with the backpressure form.
