### ISSUE TITLE
Special chars returned wrong

### ISSUE THREAD

**Issue by augustosnk12** [hgourvest/node-firebird#334]
Hello there! I got some issue here and I'd really appreciate some help: I'm using the prop `blobAsText: true` in order to retrieve string data. The problem is that some special characters are returned as a strange symbol -> `BACON S�INO MANTA`, which cause errors in my node application. The correct returned data should be `BACON SÚINO MANTA`. 

How can I handle this?

**Comment by mateusvieites** [comment]
My solution to this is
#335 

PT-BR: Também tive esse problema então tive que fazer isso, também é válido colocar latin1 no index.js default_encoding, já coloquei um pull para criar uma opção para isso :)
