### ISSUE TITLE
Instantly close all the connections

### ISSUE THREAD

**Issue by pk-bt** [hgourvest/node-firebird#345]
Is there a way to close all the connections to the database?

The situation is the following : 

I am running a firebird connection pool in a nextjs app and I want to close the all connections instantly to do some operations on the database, then reconnect node-firebird. Is this thing possible with node-firebird?

I have tried with Service Manager shutdown but I get errors. 

I use firebird version 3.

**Comment by FabianoCastro** [comment]
const aPool = pool(ISDados.MaximoPool, options);

......
.
.
.
...

aPool.destroy();

**Comment by pk-bt** [comment]
> const aPool = pool(ISDados.MaximoPool, options);
> 
> ...... . . . ...
> 
> aPool.destroy();

So simple and effective...

Thank you.
