### ISSUE TITLE
Query problem with field type CHAR

### ISSUE THREAD

**Issue by veivaa** [hgourvest/node-firebird#48]
After upgrading to node-firebird@0.2.6 (or @0.3.0) queries with field type CHAR does not work any more. After the query method they never call the query callback function. If I downgrade to node-firebird@0.2.5 it works. 

  This problem seems to occure when the result set has a field with type CHAR (not VARCHAR, but CHAR). I can reproduce the problem with this example table:
* create a new table and insert a row : 

```
    create table testtable ( field1 int, field2 varchar(80), field3 char(80), field4 char(1), field5 varchar(1)); 
    insert into testtable values (1, ’Test1’, ’Test1’, ’T’, ’T’);
```

* do a node-firebird program with query ”select field1, field2, field3, field4, field5 from testtable”. The program hangs after executing the db.query-method.
* change the query by removing field3 and field4 (char-typed fields) and run the program. It works fine.

  The problem seems to come from the commit  d0cbb6b02ab8c1d62ecfb0cf13035135e3b5b936 to lib/index.js:row 593 on 2014-11-14 changing the way string fields are read from the socket. When changing the lines from this commit back to 0.2.5 it works again. I noticed also that the version 0.2.5 returned four characters long fixed string for a char(1) so the result length was not correct in the old version.
 
  I’m using Node version 0.10.33 and Firebird version 2.5.3. The database character set is win1252 but it seemed to work similarly with utf-8. Please ask if you need any additional information about the problem or my environment. 

  Thanks for a great node module! :-)

**Comment by flakekun** [comment]
Changing 
```
var ret = data.readString(DEFAULT_ENCODING); 
```
back to 
```
var ret = data.readText(this.length, DEFAULT_ENCODING);
```
in SQLVarText.prototype.decode function resolved this problem for me.

**Comment by mariuz** [comment]
try the version from git , i publish a new version that solves it
