### ISSUE TITLE
running query in async

### ISSUE THREAD

**Issue by slachtar** [hgourvest/node-firebird#49]
Hello,
I've a real time app that receives data (via network) from sensors and need to insert it into firebird db.
I'm creating connection to db via attach method and then run queries like this:

//insert into table
var sql_txt1 = "EXECUTE PROCEDURE INSERT_POS(" +....;
dbcon.query(sql_txt1, null, function(err, result){
	    if (err) console.log("error in insert_pos:" + err + ":" + sql_txt1);
});
	    		
//update 
var sql_txt2 = "EXECUTE PROCEDURE UPDATE_COUNT(" +....;
dbcon.query(sql_txt2, null, function(err, result){
	    if (err) console.log("error in update_count:" + err + ":" + sql_txt2);
});

In the begining, things go fine, but when a big number of sensors start sending data, I receive (sometimes) messages telling that no transaction handle and that the transaction must be started explicit, which leads to data loss which may be critical in some situations.

I guess the problem comes from query being executed when previous query wasn't commited yet. Does the module automatically starts a new transaction with each new query or should I start them manually and how?

thank you

**Comment by ericlovescode** [comment]
Have you thought about using a queue?

**Comment by slachtar** [comment]
Queue solved my problem, thank you.

**Comment by josemateuss** [comment]
Hey @slachtar can you share how do you resolve your problem with async I'm having a similar problem.
