### ISSUE TITLE
Bulk insert example?

### ISSUE THREAD

**Issue by serjrd** [hgourvest/node-firebird#63]
After going through the examples and reading the description I'm still uncertain.
What would be a proper way to insert multiple (several thousands) rows with node-firebird?

**Comment by tomcon** [comment]
Have just added this to the wiki: 
"Example of one way to perform Bulk Inserts"
https://github.com/hgourvest/node-firebird/wiki/Example-of-one-way-to-perform-Bulk-Inserts

**Comment by mariuz** [comment]
@tomcon Thank you

**Comment by askanhan** [comment]
I was looking for something that could be done in one command like:

INSERT INTO tbl_name (a,b,c) VALUES(1,2,3),(4,5,6),(7,8,9) ...

But what shown in the example, is currently the only way, I think.
