### ISSUE TITLE
Query result return String values how to: {"type":"Buffer","data":[...

### ISSUE THREAD

**Issue by webjoel** [hgourvest/node-firebird#65]
After updating the node-firebird for the 0.6.1 version, the results with text values are returning to:

{"type":"Buffer","data":[...

I changed the index.js file, line 839 to:
```javascript
SQLVarString.prototype.decode = function(data) {
    
    var ret = data.readString(DEFAULT_ENCODING);
    
    if (!data.readInt()) {
        return ret;
    }
    
    return null;
};
```
and started functioning normally.

I'm using Windows 8.1, 0.12.2 Node.js and Firebird 2.5.3.

**Comment by webjoel** [comment]
I believe that the part I quoted did not need to be reversed, since undid the revert and returned to work.

I mean, the function "SQLVarString" in commit https://github.com/hgourvest/node-firebird/commit/696668d904a8dd81c1e1abfb69d68d12391d7deb

**Comment by mariuz** [comment]
published 0.6.2 please test

**Comment by webjoel** [comment]
Test success!!

Please, increment version of package.json

**Comment by hgourvest** [comment]
please revert this, if the user missed to set a character set on the field he can still convert the Buffer object to a string. This change prevent usage of binary VARCHAR fields.

**Comment by webjoel** [comment]
And my problem? I'll have to convert column by column?

**Comment by webjoel** [comment]
And my problem? I'll have to convert column by column?

**Comment by tomcon** [comment]
I'm not sure about the details here but isn't this lib only meant to work with FB 2.5 and above?

If so, isn't it considered bad not to specify a character set (at the database level) and we should no longer see use of CHARACTER SET NONE? (In fact, I'm still having errors converting a 2.1 db with CHAR SET NONE to FB 2.5)

Also, realistically, how often are varchar fields likely to hold binary data and shouldn't they be using something else (like octets)?

**Comment by hgourvest** [comment]
In my own opinion, a database driver don't have to adapt to bad practices, there is too many ways to make something wrong, and of course they are not all consistent :)
I suggest you to use fbclone (https://github.com/zedalaye/fbclone) to fix your charsets problems.
Perhaps an option on the Database connexion could be added to force the the function to return a string in all cases, I don't like it but at least the default behaviour will not be wrong.

**Comment by GuilhermeLessa** [comment]
This function may be useful by converting the query result on pre event. help me improve it. 

```
connection.on('result', function (results) {
    if (results.length) {
        const keys = Object.keys(results[0]);
    
        for (let row = 0; row < results.length; row++) {
            for (let colum = 0; colum < keys.length; colum++) {
                if (typeof results[row][keys[colum]] == 'object')
                    results[row][keys[colum]] = results[row][keys[colum]].toString();
            }
        }
    }
});
```

1. Maybe this is not very safe. Can this convert columns you shouldn't?
`if (typeof results[row][keys[colum]] == 'object')`
If we could get table schemma to filter types VARCHAR, TEXT, BLOB... Maybe it would be better.

2. Maybe map function is better?

**Comment by tomcon** [comment]
This may help:
https://github.com/hgourvest/node-firebird/wiki/Converting-results-from-arraybuffers-to-string-values

**Comment by GuilhermeLessa** [comment]
@tomcon 
Interesting, but I like the idea of ​​automating this with on results event, so don't have anything working in the query function. Understand?
