### ISSUE TITLE
Strings returned as arrays

### ISSUE THREAD

**Issue by swdevlin** [hgourvest/node-firebird#67]
Hi,

I am running Firebird 2.5. When I fetch char or varchar columns the data comes back as an array instead of a sting. I need to do something like 

```javascript
var s = '' + records[i].field;
```
in order to get a string.

Is there something I should be doing when setting up my connection?

**Comment by mariuz** [comment]
I guess you need to convert to string

**Comment by hgourvest** [comment]
you missed to define a CharacterSet on the field, you should fix your database first.
If you don't, you will have transliteration errors because NodeJs is unicode and you probably filled your database using a local code page.

**Comment by swdevlin** [comment]
Thanks. I updated the domains to be UTF8 and things are working.
