### ISSUE TITLE
What about zebedee?

### ISSUE THREAD

**Issue by zonetti** [hgourvest/node-firebird#72]
Is there a way to connect to the firebird database through [zebedee](http://www.firebirdsql.org/file/documentation/third_party_docs/firebird_zebedee.pdf)?

**Comment by mariuz** [comment]
Yes there are a few tutorials how to setup zebedee tunnel for firebird

**Comment by zonetti** [comment]
Sorry, I should had been more specific. We already use zebedee and it works fine. But when trying to connect to it with node-firebird we get ETIMEDOUT. That's why I started to think that zebedee might be the problem.
