### ISSUE TITLE
VARCHAR columns are returned as node Buffer objects?

### ISSUE THREAD

**Issue by jdabbs003** [hgourvest/node-firebird#73]
Playing around with 0.6.6, **VARCHAR** fields now come back as Node **Buffer** objects instead of strings.  Is there any option to keep using strings?  The new design seems like it would break backward compatibility with previous versions.  Or am I missing something?

**Comment by hgourvest** [comment]
https://github.com/hgourvest/node-firebird/issues/67
https://github.com/hgourvest/node-firebird/issues/65
