### ISSUE TITLE
how can I check type of data ?

### ISSUE THREAD

**Issue by paulhendrix** [hgourvest/node-firebird#75]
Hello, how can I check type of data contained in column returned from query method? 
Thanks in advance for tips.

**Comment by mariuz** [comment]
I would use typeof 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof

**Comment by paulhendrix** [comment]
Actually I was thinking of reading SQL data types.
Eg. Select * from table_name
and reading the SQL data type of each column sql, (integer, varchar etc.)
are you planning such an option?
