### ISSUE TITLE
Using rdb$db_key with node-firebird

### ISSUE THREAD

**Issue by pvilas** [hgourvest/node-firebird#76]
I want to use rdb$db_key to identify table rows on the browser.  The select rdb$db_key returns an array of bytes that I decode like a readable hex string.

>select rdb$db_key from .....

```javascript
 function keyToHex(key) {
   var h=''
   for (var a=0; a<key.length; a++) {
      var t=key[a].toString(16)
      if (t.length==1) t='0'+t
      h=h.concat(t)
   }
   return h
 }
```

e.g. renders d500000001000000

Then, I use this string to encode the key on the server with

```javascript
        hexToKey: function(hex) {
            var buffer=new ArrayBuffer(hex.length)
            var ui=new Uint16Array(buffer)
            var g=0
            for (var i=0; i<hex.length; i+=2) {
                ui[g]=parseInt(hex.substr(i,2), 16)
                g+=1
            }
            return ui
        },
```

That gives an int array like { '0': 213, '1': 0, '2': 0, '3': 0, '4': 1, '5': 0, '6': 0, '7': 0 }

Now, we would use this key to find out the row

```javascript
            var d=[]
            d.push(db.hexToKey(req.params.pk))

           db. query('select * from iva_periodo where rdb$db_key=?', d, function(err, rs) {
                ...
```

But the query terminates with a -303 error

                             
>Error: Dynamic SQL Error, SQL error code = -303, arithmetic exception, numeric overflow, or string truncation, string right truncation

Any idea?

**Comment by tomcon** [comment]
Looks like "d" it should be a char(8) parameter (and quoted) instead of an int array when selecting from a single table.

> You must use a char data type of the correct length 
   (For tables: 8 bytes.)
   (For views: 8 times the number of tables referenced in the view definition.)
> One of the things that most confuses people not used to db_key is the fact almost all the time it needs to be qualified explicitly with the table name. For example ...

http://ibexpert.net/ibe/index.php?n=Doc.TheMysteryOfRDBDBKEY

**Comment by pvilas** [comment]
That's it! 

```sql
select descripcion from familias where familias.rdb$db_key=x'"+keyToHex(key).toUpperCase()+"'"
```
does the job. The only thing is cannot bind as a parameter but this is a minor question. 

Thank you very much Tom!
