### ISSUE TITLE
connection to Firebird DB

### ISSUE THREAD

**Issue by turalgulmammadov** [hgourvest/node-firebird#77]
Hi guys,
I have attached my code and error message on the below. Can you please help me, I could not find the reason to get the error.
Thanks,
```
 // Node-Firebird
var Firebird = require('node-firebird');
// Options
var options = {};
//options.host = '127.0.0.1';
//options.port = 3050;
options.database = 'mydb.FDB';
options.user = 'SYSDBA';
options.password = 'masterkey';
// Query
Firebird.attach(options, function(err, db) {

    if (err)
        throw err;

    // db = DATABASE
    db.query('SOME QUERY', function(err, result) {
        // IMPORTANT: close the connection
        db.detach();
    });

});
```

> // Error message
/Users/bla/myfile.js:14
        throw err;
              ^
Error: I/O error during "open" operation for file "/Users/bla/mydb.FDB", Error while trying to open file
    at doCallback (/Users/bla/node_modules/node-firebird/lib/index.js:1233:18)
    at /Users/bla/node_modules/node-firebird/lib/index.js:2897:21
    at /Users/bla/node_modules/node-firebird/lib/messages.js:151:25
    at search (/Users/bla/node_modules/node-firebird/lib/messages.js:117:13)
    at /Users/bla/node_modules/node-firebird/lib/messages.js:54:21
    at FSReqWrap.wrapper [as oncomplete] (fs.js:527:17)

**Comment by tomcon** [comment]
Looks like it can't connect to the database. Things to try: 
- check firebird is actually running 
- can you connect to it using isql.exe or flamerobin using the same credentials
- doesn't seem to like the database name 
- or database file corrupt or not in that location
- check case-sensitivity on linux

**Comment by turalgulmammadov** [comment]
Actually, I can connect the same database with :
```
var con = fb.createConnection();
con.connectSync('mydb.FDB', 'SYSDBA', 'masterkey', '');
var rs = con.querySync('SOME QUERY'); 
```
And when I am trying to connect via Flamerobin, it works perfectly as well. This is really weird error I guess. Any other suggestions, please?

**Comment by mariuz** [comment]
you need to check the connection with localhost from both flamerobin and node-firebird driver , also the firebird is using usually a user with it's own user , you need to make sure that file permissions are granted for it (usually others should be granted rw access)

in secondary example you are using the c++ driver that is using fbclient so it can access the file without the need to connect to localhost

**Comment by elgubenis** [comment]
isql-fb lets me connect, when i use it with sudo, without sudo it does not connect me

my node process is running with sudo, but cannot connect

**Comment by elgubenis** [comment]
```connect '/home/ec2-user/data-interface/fdbs/ABC.fdb' user 'SYSDBA' password 'masterkey';```
works with sudo isql-fb

while node-firebird says: ```Error: I/O error during "open" operation for file "/home/ec2-user/data-interface/fdbs/ABC.fdb", Error while trying to open file```

**Comment by elgubenis** [comment]
i tried firebird:firebird chown as well as root etc.
