### ISSUE TITLE
Node-firebird sequentially select

### ISSUE THREAD

**Issue by turalgulmammadov** [hgourvest/node-firebird#78]
I am trying to get the data from Firebird DB with sequentially select option. I would like to get the first 500 rows, as you see on my code. And for testing, I am increasing 'k' for each 'row' and logging 'k' and 'md5' to the console.

When I am running my code, it gives me random number of rows. But the number of rows are always more than 500.

How can I solve this problem? Any suggestions?
```
var Firebird = require('node-firebird');
var md5 = require('md5');
var options = {};
//options.host = '127.0.0.1';
//options.port = 3050;
options.database = '/Users/bla/mydb.FDB';
options.user = 'SYSDBA';
options.password = 'masterkey';
var pool = Firebird.pool(10, options);
var k = 0;
pool.get(function (err, db) {

  if (err)
    throw err;
  db.sequentially('SELECT FIRST 500 SOME QUERY', function (row, index) {
    k = k + 1;
    console.log(k + ' => ' + md5(JSON.stringify(row)) + '\n');
  }, function (err) {
    db.detach();
  });
});
```

**Comment by sdnetwork** [comment]
it's a bug in node-firebird, i have a fix for this problem.

i will post it soon here.

**Comment by turalgulmammadov** [comment]
Thanks! 
It works!

**Comment by turalgulmammadov** [comment]
@sdnetwork I am using the driver that you have provided on above. 
It works, everything is fine. But it returns the strings as a buffer. When I am converting them to string via .toString : 
``` 
JSON.stringify(row.mycolumn.toString('utf8'));
// or row.mycolumn.toString('utf');
```
my application just freezing when it's trying to convert 'NULL' objects.

Any suggestions?

**Comment by mariuz** [comment]
@sdnetwork Could make a pull request . Thanks for the fix
