### ISSUE TITLE
startTrace

### ISSUE THREAD

**Issue by elgubenis** [hgourvest/node-firebird#83]
hi folks,
i want to start a trace session for the service manager, but im not sure how to pass the configfile value, if i put a path starting with / there i get an error, (im on mac osx)
<img width="1112" alt="screen shot 2015-10-25 at 14 01 38" src="https://cloud.githubusercontent.com/assets/7453396/10717535/f102855e-7b20-11e5-8dc6-783d7d13693f.png">

**Comment by elgubenis** [comment]
the code:
```coffee
Firebird = require 'node-firebird'

options =
  host: '127.0.0.1'
  port: 3050
  database: '/Users/lgubenis/projects/lab/firebird/Ejemplos.fdb'
  user: 'sysdba'
  password: 'masterkey'
  manager: true

Firebird.attach options, (err, db) ->
  return console.error err if err

  traceOptions =
    configfile: '/Users/lgubenis/projects/lab/firebird/fb.conf'
    tracename: 'ejemplos'

  db.startTrace traceOptions, (err, stream) ->
    stream.on 'data', (data) ->
      console.log data.toString()
```

**Comment by hgourvest** [comment]
ok

**Comment by sdnetwork** [comment]
Maybe it's because, the sc wait the content of config file and not the path i will check

**Comment by sdnetwork** [comment]
I confirm the problem, the sc attemp the file content !

i try to solve this issue asap

**Comment by elgubenis** [comment]
any news on that? how could i help?

**Comment by sdnetwork** [comment]
sorry i don't have time for moment, you can try to modify the startTrace by replacing the

    blr.addString2(isc_spb_trc_cfg, configfile, DEFAULT_ENCODING);
by
    blr.addString2(isc_spb_trc_cfg, fs.readFileSync(configfile).toString(), DEFAULT_ENCODING);

it's not a definitive solution, but it could help you to see if the problem is there
