### ISSUE TITLE
TypeError: svc.backup is not a function

### ISSUE THREAD

**Issue by LibreTitan** [hgourvest/node-firebird#85]
var Firebird = require('node-firebird');

var _connection = {
    user : 'SYSDBA',
    password : 'masterkey',
    host : 'localhost',
    port : 3050,
    database : 'neodbex',
    manager : true
}

Firebird.attach(_connection, function(err, svc) { 
    if (err)
        return;
    svc.backup(
        {
            database:'NeoDB', //alias
            files: [
                    {
                     filename:'/DB/MYDB.FBK', 
                     sizefile:'0'
                    }
                   ]
        }, 
        function(err, data) {
            console.log(data);
        });
});

=============================================================================
TypeError: svc.backup is not a function

**Comment by sdnetwork** [comment]
witch version of node-firebird are you using ?

**Comment by LibreTitan** [comment]
so simple. thx
