### ISSUE TITLE
Lowercase only aliases

### ISSUE THREAD

**Issue by matheusd** [hgourvest/node-firebird#87]
When doing a select with aliases, the returned column names are all lowercased. For example:

  select 1 as "Field ONE" from rdb$database;

returns an object with an attribute "field one" instead of "Field ONE".

I was able to fix this by removing the appropriate toLowerCase() call, but was wondering if there is a particular reason for this behavior (before submitting a pull request).

**Comment by mariuz** [comment]
I have removed it in master , I will release a new version with the fix

**Comment by mariuz** [comment]
Fixed by 1d62471f6c6235ae10de735a168c071d38d19591

**Comment by matheusd** [comment]
Hey, thanks a lot!

**Comment by marinintim** [comment]
It should be major version bump, according to semver.

It breaks compatibility to all code that uses lowercase, it should not be released as minor version.
