### ISSUE TITLE
node-firebird connect failed...

### ISSUE THREAD

**Issue by Yoohwan** [hgourvest/node-firebird#90]
![1](https://cloud.githubusercontent.com/assets/17820558/13735252/89a26062-e9ea-11e5-959a-681d79e90255.png)

node : node 4.3.2
firebird : 2.5.1 x86
OS : window 8 x86

ERROR : Inalid clumplet buffer structure : string length doesn't match with clumplet
any search I can not find too.
I do not know what is the cause.
Successful FLameRobin Tool connection.

souse code : 
var Firebird = require('node-firebird');
var db_con = {};
db_con.host = '127.0.0.1';
db_con.database = __dirname + '/../data/MAIN.fdb'; or  'c:/TEST/MAIN.fdb';
db_con.user = 'SYSDBA';
db_con.password = 'masterkey';

Firebird.attach(db_con, function(err, db){
     if(err) console.log('Failed to get connection firebird' + err);
     else console.log('Succed to get connection firebird');
});

Thank you in advance.

**Comment by flakekun** [comment]
I think, I encountered this error when windows username contained non ASCII symbols (cyrillic for example). Try running your node app under full english windows username.

**Comment by Yoohwan** [comment]
Thanks..!!!!! 
i have  resolved to change the english windows username
