### ISSUE TITLE
Async DB queries using wrong db context

### ISSUE THREAD

**Issue by EmileSpecs** [hgourvest/node-firebird#91]
I have a query wrapper that executes many queries synchronously against more than one DB file, but the wrapper function gets called asynchronously via an API.

In the wrapper I call a connect function before each query:
```
var dbPools = {};
function connect(database, callback) {
    var connstring = app.dataSources.firebird.settings;
    var pool = dbPools[database] || null;
    connstring.database = database;

    if (!pool) pool = dbPools[database] = require('node-firebird').pool(1, connstring);
    pool.get(callback);
}


my.query = function(databases, sqlquery, bind, processResult, callback) {
  async.eachSeries(databases, function(database, next_database) {
  // this is called inside my wrapper function
  connect(database.path, function(err, db) {
     if (db.connection.options.database !== database.path) return done(new Error('Databases do not  match for query!'));
     db.query(sqlquery, bind, function (err, result) {
        db.detach();
        processResult(result);
        next_database(err);
     });
  });
  }, function(err) {
    callback(err);  
  });
});
```

When more than one API call requires results from different DB's, it seems like the second query sets the DB connection to another DB and the first call then uses that DB for it's query. I then get the `"Databases do not  match for query!"` error.
That of course causes major issues, since the query is run against the wrong DB.

I assumed that the pool would return a DB object with it's own socket to the appropriate DB and that they would execute asynchronously without issues, but the calls somehow "cross wires" and I can't get it to work!

Is the approach above supposed to work? Is it an issue with node-firebird? Or is there something wrong with the architecture of my code?

Any help please!

**Comment by EmileSpecs** [comment]
So I've tried to figure this out and have found a possible issue and I don't know why it's happening.

When a new pool is created the database file used is the correct one, I've determined it with a console output. For my testing I'm connecting to two different DB files, thus creating two pools.

When connect get's called subsequently, the database file for both pools are the same. Somehow when the second pool is created it overwrites the first pool's database file value.
```
pools { SQL:
   Pool {
     internaldb: [ [Object] ],
     pooldb: [ [Object] ],
     dbinuse: 0,
     max: 2,
     pending: [],
     options:
      { host: '192.168.1.5',
        database: 'C:\\...\\SQL1\\MDLDATA.FDB',
        password: '***',
        name: '***',
        user: '***',
        debug: false,
        isPool: true } },
  'SQL 1':
   Pool {
     internaldb: [ [Object] ],
     pooldb: [ [Object] ],
     dbinuse: 0,
     max: 2,
     pending: [],
     options:
      { host: '192.168.1.5',
        database: 'C:\\...\\SQL1\\MDLDATA.FDB',
        password: '***',
        name: '***',
        user: '***',
        debug: false,
        isPool: true } } }
```

So the first pool is supposed to be `C:\\...\\SQL\\MDLDATA.FDB`, but is the same as the second pool.

Why is this happening? I can see via console that each pool is only created once, so it must be overwritten in node-firebird...

**Comment by sdnetwork** [comment]
hello,

i think your problem is here : 
   
    var connstring = app.dataSources.firebird.settings;

you change each time you call connect function the same object (node-firebird don't clone the options object)

     connstring.database = database;

**Comment by EmileSpecs** [comment]
Oh snap, thanks @sdnetwork!

That seems to have solved it for me! Will test some more and reopen if necessary...
