### ISSUE TITLE
I can not make queries firebird 2.0.6

### ISSUE THREAD

**Issue by samuelfaria** [hgourvest/node-firebird#93]
I'm using the 2.0.6 version of firebird.
I can make a connection with the bank with no problems, but when I perform the query do not have any feedback or error or callback.

I've read some things about the base being in WIN1252 and needs to be UTF-8, but this version of firebird not support.

Li also a note in the documentation that needs to be version 2.5 or above firebird.

Is there something I can do to run queries?

This is my code:
```
var Firebird = require('node-firebird');
var pool = Firebird.pool(5, config.firebird.options);

  pool.get(function (err, db) {
    if (err) {
      return callback(err);
    }
    
	db.query('select * from sup001', function (err, results) {
      if (err) {
        return callback(err);
      }
      db.detach();
      callback(null, results);
    });
  });

```

**Comment by mariuz** [comment]
Please upgrade to firebird 2.5/30  , 2.0.x is not supported
