### ISSUE TITLE
TypeError: svc.backup is not a function

### ISSUE THREAD

**Issue by VZiemer** [hgourvest/node-firebird#96]
Firebird.attach(options, function(err, svc) {
      if (err)
          return;
      svc.backup(
          {
              database:'test.fdb',
              files: [
                      {
                       filename:'test.fbk',
                       sizefile:'0'
                      }
                     ]
          },
          function(err, data) {
              console.log(data);
          });
    });

when I use the example this error occurs:

Application has thrown an uncaught exception and is terminated:
TypeError: svc.backup is not a function
node-firebird version 0.7.2.

which the parameter should I pass the svc?

Thanks.

**Comment by igarcez** [comment]
try to add to the attach options manager = true

**Comment by VZiemer** [comment]
Thanks, it's work.
