### ISSUE TITLE
typescript definition files

### ISSUE THREAD

**Issue by hozjanmarko** [hgourvest/node-firebird#98]
I wonder if you could provided typescript definition files for the DefinitelyTyped repo.
I'm currently using my own definitions(https://github.com/hozjanmarko/node-firebird-dts), but it would be very helpfull, if we could get the typings directly through tds(https://github.com/DefinitelyTyped/tsd) or typings(https://github.com/typings/typings).

**Comment by calvin** [comment]
This is a definition that I wrote: https://gist.github.com/calvin/b4c8df06c898d637e1076d3afafb5ad7.

If possible, I think it is good to be included in the package than pushing the definitions to https://github.com/DefinitelyTyped/DefinitelyTyped 

@maintainers Have a look at http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html and https://github.com/typings/typings/blob/master/docs/faq.md#should-i-use-the-typings-field-in-packagejson

**Comment by mariuz** [comment]
Please review the one that we added 

https://github.com/hgourvest/node-firebird/blob/master/index.d.ts

**Comment by hozjanmarko** [comment]
Great work
