### ISSUE TITLE
 Firebird-3.0.0.32483 - The problem with the request Queries

### ISSUE THREAD

**Issue by khusamov** [hgourvest/node-firebird#99]
The problem with the request Queries in the Firebird-3.0.0.32483-0

```
Unhandled rejection Error
    at doCallback (\node_modules\node-firebird\lib\index.js:1233:18)
    at \node_modules\node-firebird\lib\index.js:2928:21
    at \node_modules\node-firebird\lib\messages.js:151:25
    at search (\node_modules\node-firebird\lib\messages.js:117:13)
    at \node_modules\node-firebird\lib\messages.js:54:21
    at FSReqWrap.wrapper [as oncomplete] (fs.js:675:17)
```

The connection runs fine, but when querying this error.

firebird.conf Settings:
```
#AuthServer = Legacy_Auth
WireCrypt = Disabled
```
Option AuthServer had to turn off as her connection fails.

If a server option to set the `AuthServer = Legacy_Auth`, an error occurs:

`Your user name and password are not defined. Ask your database administrator to set up a Firebird login.`

**Comment by khusamov** [comment]
In index.js file fished message number.

`2926 > messages.lookupMessages(obj.status, function(message) {`

`obj.status = 335545106`

http://tracker.firebirdsql.org/browse/JDBC-428

**Comment by khusamov** [comment]
If a server option to set the Auth Server = Legacy Auth, an error occurs:

`Your user name and password are not defined. Ask your database administrator to set up a Firebird login.`

**Comment by mariuz** [comment]
To setup a user for the legacy authentication, you need to change the UserManager in the firebird.conf to:

UserManager = Srp, Legacy_UserManager

**Comment by khusamov** [comment]
Enable the option UserManager = Srp, Legacy_UserManager.
remaining errors.
IBExprert not connected.
node-firebird also not connected.
The same error:

![image](https://cloud.githubusercontent.com/assets/4146998/15887201/98b0d6c0-2d69-11e6-9673-be30b0d85dde.png)

**Comment by mariuz** [comment]
Seems that you need Legacy_UserManager first 

https://github.com/FirebirdSQL/jaybird/wiki/Jaybird-and-Firebird-3

**Comment by khusamov** [comment]
First in list options?

```
UserManager = Srp, Legacy_UserManager
AuthServer = Legacy_Auth
WireCrypt = Disabled
```

Or first in values  `UserManager = Legacy_UserManager, Srp`?

Does not help(

**Comment by khusamov** [comment]
With such options ibexpert connected, and node-firebird is not connected:
```
UserManager = Legacy_UserManager, Srp
AuthServer = Legacy_Auth, Srp
WireCrypt = Disabled
```

**Comment by mariuz** [comment]
http://firebird-net-provider.narkive.com/csO3XR2B/connecting-to-firebird-3-0-alpha-2#post2

Next you need to create another SYSDBA account (using gsec) so it
also exists as a legacy user. I am not 100% sure if you only need to do
"gsec -user sysdba -password masterkey", or that you explicitly need to
do "add sysdba -pw masterke" from the gsec prompt

**Comment by khusamov** [comment]
Thank you earned!

But now the tables are not visible.

Dynamic SQL Error, SQL error code = -204, Table unknown, PRODUCT, At line 1, column 15

I gave the second user rights, but it does not see the table. But in ibexpert table shows, if the second user to log into.
